## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [4]:
app_train.info()
#row數 = 307511 , column數 = 122

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [14]:
(r,c) = app_train.shape
print('row數=%.0f , column數=%.0f ' %(r,c))

row數=307511 , column數=122

#### 列出所有欄位

In [16]:
app_train.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

In [18]:
col_lst = app_train.columns.tolist()
col_lst

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

#### 截取部分資料

In [11]:
app_train.iloc[100:150,]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
100,100119,0,Revolving loans,F,N,Y,0,54000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
101,100120,0,Cash loans,F,N,N,0,135000.0,781920.0,28215.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
102,100121,0,Cash loans,M,N,Y,0,126000.0,787131.0,26145.0,...,0,0,0,0,1.0,1.0,0.0,0.0,0.0,1.0
103,100122,0,Cash loans,F,N,N,1,76500.0,808650.0,26217.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
104,100123,0,Cash loans,F,N,N,0,103500.0,675000.0,19737.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
105,100124,0,Cash loans,M,N,Y,0,225000.0,448272.0,28647.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
106,100125,0,Cash loans,F,N,N,0,126000.0,263686.5,26208.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
107,100126,0,Revolving loans,M,N,Y,2,135000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
108,100127,0,Cash loans,M,N,Y,0,112500.0,52128.0,5341.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
109,100129,0,Revolving loans,F,Y,Y,1,85500.0,135000.0,6750.0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0
110,100130,1,Cash loans,F,N,Y,1,157500.0,723996.0,30802.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
111,100131,0,Cash loans,F,N,Y,0,270000.0,891072.0,45625.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
112,100132,0,Cash loans,F,N,Y,0,202500.0,1136439.0,73611.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
113,100133,0,Cash loans,F,N,N,0,67500.0,384048.0,18810.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
114,100134,0,Revolving loans,F,N,N,0,202500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
115,100135,0,Cash loans,M,N,Y,0,135000.0,391194.0,26271.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
116,100136,0,Cash loans,M,Y,N,1,157500.0,1571931.0,49356.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
117,100137,0,Cash loans,F,Y,Y,0,225000.0,891072.0,45625.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
118,100138,0,Cash loans,M,Y,N,0,135000.0,824823.0,29223.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
119,100139,0,Cash loans,F,N,N,1,157500.0,302341.5,24016.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
120,100140,0,Revolving loans,F,N,N,0,157500.0,675000.0,33750.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
121,100142,0,Cash loans,M,Y,Y,1,360000.0,579195.0,27994.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
122,100143,0,Revolving loans,M,N,Y,0,162000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
123,100144,0,Cash loans,F,N,N,0,112500.0,535500.0,30028.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
124,100145,0,Cash loans,F,Y,Y,1,202500.0,260725.5,16789.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
125,100146,0,Cash loans,M,Y,Y,0,117000.0,327024.0,12456.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
126,100147,0,Cash loans,F,N,Y,1,135000.0,518562.0,22099.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
127,100148,0,Cash loans,F,N,Y,0,247500.0,755190.0,36459.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
128,100149,0,Cash loans,M,Y,N,0,171000.0,539590.5,26374.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
129,100151,0,Cash loans,M,N,N,0,135000.0,182016.0,11772.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
130,100152,0,Cash loans,F,N,Y,0,157500.0,254412.0,9720.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
131,100153,0,Cash loans,M,Y,Y,0,202500.0,1107981.0,32526.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
132,100154,0,Revolving loans,M,N,N,0,144000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
133,100155,0,Cash loans,M,N,N,0,157500.0,675000.0,21906.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
134,100156,0,Cash loans,F,Y,N,2,157500.0,945000.0,39127.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
135,100157,0,Cash loans,M,N,Y,0,180000.0,1755000.0,61132.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
136,100158,0,Cash loans,M,N,N,0,180000.0,590337.0,27486.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
137,100159,0,Cash loans,F,N,Y,0,225000.0,1515415.5,41800.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
138,100160,1,Cash loans,M,N,Y,0,292500.0,675000.0,36747.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
139,100161,0,Cash loans,F,N,Y,0,90000.0,370629.0,13972.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
140,100162,0,Cash loans,F,N,Y,0,112500.0,547344.0,18216.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
141,100163,0,Cash loans,F,N,Y,0,130500.0,550489.5,19773.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
142,100164,0,Cash loans,F,Y,N,1,450000.0,407434.5,43362.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
143,100165,0,Cash loans,F,Y,Y,0,175500.0,1293502.5,35568.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
144,100166,0,Cash loans,F,N,Y,3,58500.0,152820.0,15241.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
145,100167,0,Cash loans,F,N,Y,0,180000.0,427500.0,46170.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
146,100173,0,Cash loans,F,N,N,0,117000.0,781920.0,26725.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
147,100174,0,Revolving loans,F,N,Y,2,180000.0,225000.0,11250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
148,100175,0,Cash loans,F,N,Y,1,202500.0,1251072.0,45067.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
149,100176,0,Cash loans,F,N,Y,0,135000.0,1078200.0,31653.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子